DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (CHECK
    user_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
);